name: 🔗 GHA

on: [push, pull_request]

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create file with content
        run: echo "This is my file content" > my_file.txt

      - name: Upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: my-artifact
          path: my_file.txt

  release:
    needs: create-and-upload-artifact
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download artifact
        uses: actions/download-artifact@v2
        with:
          name: my-artifact

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: ./my_file.txt
          body: "This is a V-Sekai/V-Sekai.test-github-actions release"
          generate_release_notes: true
          append_body: true
