name: 🔗 GHA

on: [push, pull_request]

jobs:
  create-and-upload-artifact:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Create placeholders
        run: |
          echo "Creating placeholders..."
          echo "This is a placeholder for game.exe" > game.exe
          echo "This is a placeholder for game_editor.exe" > game_editor.exe
          echo "This is a placeholder for game.pck" > game.pck

      - name: Upload game executable
        uses: actions/upload-artifact@v2
        with:
          name: game-executable
          path: game.exe

      - name: Upload game editor
        uses: actions/upload-artifact@v2
        with:
          name: game-editor
          path: game_editor.exe

      - name: Upload game pck
        uses: actions/upload-artifact@v2
        with:
          name: game-pck
          path: game.pck
  

  release:
    needs: create-and-upload-artifact
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    
    steps:
      - name: Download game executable
        uses: actions/download-artifact@v2
        with:
          name: game-executable
          path: ./artifacts/game-executable

      - name: Download game editor
        uses: actions/download-artifact@v2
        with:
          name: game-editor
          path: ./artifacts/game-editor

      - name: Download game pck
        uses: actions/download-artifact@v2
        with:
          name: game-pck
          path: ./artifacts/game-pck

      - name: Release
        uses: softprops/action-gh-release@v1
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: |
            ./artifacts/game-executable/game.exe 
            ./artifacts/game-editor/game_editor.exe 
            ./artifacts/game-pck/game.pck
          body: "This is a V-Sekai/V-Sekai.test-github-actions release"
          generate_release_notes: true
          append_body: true
